import covid_paper_plots as cpp
import pandas as pd


def get_states():
    states = {'Alabama': dict(country_key='AL',
                              D_01=1,
                              Plot_line=False,
                              D_10=10,
                              marker='dimgray',
                              pop=83783942),
              # 'Alaska': dict(country_key='AK',
              #                D_01=1,
              #                Plot_line=False,
              #                D_10=3,
              #                marker='dimgray',
              #                pop=11589623),
              'Arizona': dict(country_key='AZ',
                              D_01=1,
                              Plot_line=False,
                              D_10=13,
                              marker='dimgray',
                              pop=83783942),
              'Arkansas': dict(country_key='AR',
                               D_01=2,
                               Plot_line=False,
                               D_10=10,
                               marker='dimgray',
                               pop=65273511),
              'California': dict(country_key='CA',
                                 D_01=1,
                                 Plot_line=True,
                                 D_10=12,
                                 marker='red',
                                 pop=5792202),
              'Colorado': dict(country_key='CO',
                               D_01=1,
                               Plot_line=False,
                               D_10=16,
                               marker='dimgray',
                               pop=10423054),
              'Connecticut': dict(country_key='CT',
                                  D_01=1,
                                  Plot_line=False,
                                  D_10=10,
                                  marker='dimgray',
                                  pop=4937786),
              'Delaware': dict(country_key='DE',
                               D_01=1,
                               Plot_line=True,
                               D_10=10,
                               marker='dimgray',
                               pop=60461826),
              'District of Columbia': dict(country_key='DC',
                                           D_01=1,
                                           Plot_line=True,
                                           D_10=9,
                                           marker='dimgray',
                                           pop=126476461),
              'Florida': dict(country_key='FL',
                              D_01=2, Plot_line=True,
                              D_10=11,
                              marker='black',
                              pop=51269185),
              'Georgia': dict(country_key='GA',
                              D_01=1,
                              Plot_line=False,
                              D_10=10,
                              marker='dimgray',
                              pop=17134872),
              # 'Hawaii': dict(country_key='HI',
              #                D_01=1,
              #                Plot_line=False,
              #                D_10=1,
              #                marker='dimgray',
              #                pop=83783942),
              # 'Idaho': dict(country_key='ID',
              #               D_01=3,
              #               Plot_line=True,
              #               D_10=9,
              #               marker='dimgray',
              #               pop=46754778),
              'Illinois': dict(country_key='IL',
                               D_01=1,
                               Plot_line=True,
                               D_10=9,
                               marker='dimgray',
                               pop=10099265),
              'Indiana': dict(country_key='IN',
                              D_01=1,
                              Plot_line=False,
                              D_10=12,
                              marker='dimgray',
                              pop=8654622),
              # 'Iowa': dict(country_key='IA',
              #              D_01=1,
              #              Plot_line=True,
              #              D_10=11,
              #              marker='dimgray',
              #              pop=67886011),
              'Kansas': dict(country_key='KS',
                             D_01=1,
                             Plot_line=True,
                             D_10=10,
                             marker='dimgray',
                             pop=331002651),
              'Kentucky': dict(country_key='KY',
                               D_01=1,
                               Plot_line=False,
                               D_10=11,
                               marker='dimgray',
                               pop=83783942),
              'Louisiana': dict(country_key='LA',
                                D_01=1,
                                Plot_line=False,
                                D_10=10,
                                marker='dimgray',
                                pop=11589623),
              # 'Maine': dict(country_key='ME',
              #               D_01=1,
              #               Plot_line=False,
              #               D_10=7,
              #               marker='dimgray',
              #               pop=37742154),
              'Maryland': dict(country_key='MD',
                               D_01=1,
                               Plot_line=False,
                               D_10=10,
                               marker='dimgray',
                               pop=83783942),
              'Massachusetts': dict(country_key='MA',
                                    D_01=1,
                                    Plot_line=False,
                                    D_10=11,
                                    marker='dimgray',
                                    pop=65273511),
              'Michigan': {'country_key': 'MI',
                           'D_01': 1,
                           'Plot_line': True,
                           'D_10': 9,
                           'marker': 'dimgray',
                           'pop': 5792202},
              'Minnesota': {'country_key': 'MN',
                            'D_01': 1,
                            'Plot_line': False,
                            'D_10': 10,
                            'marker': 'dimgray',
                            'pop': 10423054},
              'Mississippi': {'country_key': 'MI',
                              'D_01': 1,
                              'Plot_line': False,
                              'D_10': 13,
                              'marker': 'dimgray',
                              'pop': 4937786},
              'Missouri': {'country_key': 'MO',
                           'D_01': 1,
                           'Plot_line': True,
                           'D_10': 10,
                           'marker': 'dimgray',
                           'pop': 60461826},
              # 'Montana': {'country_key': 'MT',
              #             'D_01': 1,
              #             'Plot_line': True,
              #             'D_10': 6,
              #             'marker': 'dimgray',
              #             'pop': 126476461},
              # 'Nebraska': {'country_key': 'NE',
              #              'D_01': 2,
              #              'Plot_line': True,
              #              'D_10': 5,
              #              'marker': 'dimgray',
              #              'pop': 51269185},
              'Nevada': {'country_key': 'NV',
                         'D_01': 1,
                         'Plot_line': False,
                         'D_10': 10,
                         'marker': 'dimgray',
                         'pop': 17134872},
              # 'New Hampshire': {'country_key': 'NH',
              #                   'D_01': 1,
              #                   'Plot_line': True,
              #                   'D_10': 3,
              #                   'marker': 'dimgray',
              #                   'pop': 5421241},
              'New Jersey': {'country_key': 'NJ',
                             'D_01': 1,
                             'Plot_line': False,
                             'D_10': 11,
                             'marker': 'green',
                             'pop': 83783942},
              # 'New Mexico': {'country_key': 'NM',
              #                'D_01': 1,
              #                'Plot_line': True,
              #                'D_10': 6,
              #                'marker': 'dimgray',
              #                'pop': 46754778},
              'New York': {'country_key': 'NY',
                           'D_01': 2,
                           'Plot_line': True,
                           'D_10': 17,
                           'marker': 'blue',
                           'pop': 10099265},
              'North Carolina': {'country_key': 'NC',
                                 'D_01': 2,
                                 'Plot_line': False,
                                 'D_10': 12,
                                 'marker': 'dimgray',
                                 'pop': 8654622},
              # 'North Dakota': {'country_key': 'ND',
              #                  'D_01': 1,
              #                  'Plot_line': True,
              #                  'D_10': 3,
              #                  'marker': 'dimgray',
              #                  'pop': 67886011},
              'Ohio': {'country_key': 'OH',
                       'D_01': 3,
                       'Plot_line': True,
                       'D_10': 11,
                       'marker': 'dimgray',
                       'pop': 331002651},
              'Oklahoma': {'country_key': 'OK',
                           'D_01': 1,
                           'Plot_line': True,
                           'D_10': 8,
                           'marker': 'dimgray',
                           'pop': 60461826},
              'Oregon': {'country_key': 'OR',
                         'D_01': 1,
                         'Plot_line': True,
                         'D_10': 10,
                         'marker': 'dimgray',
                         'pop': 126476461},
              'Pennsylvania': {'country_key': 'PA',
                               'D_01': 1,
                               'Plot_line': True,
                               'D_10': 8,
                               'marker': 'black',
                               'pop': 51269185},
              'Rhode Island': {'country_key': 'RI',
                               'D_01': 2,
                               'Plot_line': True,
                               'D_10': 10,
                               'marker': 'Purple',
                               'pop': 5421241},
              'South Carolina': {'country_key': 'SC',
                                 'D_01': 1,
                                 'Plot_line': False,
                                 'D_10': 9,
                                 'marker': 'dimgray',
                                 'pop': 83783942},
              # 'South Dakota': {'country_key': 'SD',
              #                  'D_01': 1,
              #                  'Plot_line': True,
              #                  'D_10': 2,
              #                  'marker': 'dimgray',
              #                  'pop': 46754778},
              'Tennessee': {'country_key': 'TN',
                            'D_01': 1,
                            'Plot_line': True,
                            'D_10': 8,
                            'marker': 'dimgray',
                            'pop': 10099265},
              'Texas': {'country_key': 'TX',
                        'D_01': 1,
                        'Plot_line': False,
                        'D_10': 12,
                        'marker': 'dimgray',
                        'pop': 8654622},
              # 'Utah': {'country_key': 'UT',
              #          'D_01': 1,
              #          'Plot_line': True,
              #          'D_10': 7,
              #          'marker': 'dimgray',
              #          'pop': 67886011},
              'Vermont': {'country_key': 'VT',
                          'D_01': 2,
                          'Plot_line': True,
                          'D_10': 10,
                          'marker': 'blue',
                          'pop': 331002651},
              'Virginia': {'country_key': 'VA',
                           'D_01': 1,
                           'Plot_line': False,
                           'D_10': 10,
                           'marker': 'dimgray',
                           'pop': 83783942},
              'Washington': {'country_key': 'WA',
                             'D_01': 1,
                             'Plot_line': True,
                             'D_10': 10,
                             'marker': 'green',
                             'pop': 46754778},
              # 'West Virginia': {'country_key': 'WV',
              #                   'D_01': 1,
              #                   'Plot_line': True,
              #                   'D_10': 2,
              #                   'marker': 'dimgray',
              #                   'pop': 10099265},
              'Wisconsin': {'country_key': 'WI',
                            'D_01': 4,
                            'Plot_line': False,
                            'D_10': 10,
                            'marker': 'dimgray',
                            'pop': 8654622},
              #'Wyoming': {'country_key': 'WY',
              #            'D_01': 0,
              #            'Plot_line': True,
              #            'D_10': 0,
              #            'marker': 'dimgray',
              #            'pop': 67886011},
              }

    return states


def get_us_data():
    # import the data, direct from Johns Hopkins github
    url = 'https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/' \
          'csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_deaths_US.csv'

    df_raw = pd.read_csv(url)
    df_raw.drop(['UID', 'iso2', 'iso3', 'code3', 'FIPS', 'Admin2', 'Lat', 'Long_', 'Combined_Key', 'Population'],
                axis=1, inplace=True)
    df = df_raw.groupby(['Province_State']).sum().transpose().copy()
    df.index = pd.to_datetime(df.index)

    return df


def main():
    df_states = get_us_data()
    df_countries = cpp.get_data()

    print(df_states['New York'].to_numpy())

    states = get_states()
    countries = cpp.get_countries()

    #for state in df.columns:
    #    print(state, df[state].to_numpy())

    # plot 1: Line plot of Number of deaths versus day in year
    plot_params_1 = {'x_lim': [50, 95],
                     'y_lim': [1, 30000],
                     'x_ticks': [50, 65, 80],
                     'y_ticks': [1, 10, 100, 1000, 10000],
                     'title': 'Number of Deaths, versus days in year',
                     'save_name': 'Day_in_year_abs'}

    cpp.plot_func(df_states, states, plot_params_1, line_style=True, time_abs=True, d_01_type=True, pop_type=False,
              best_fit_poly=None, best_fit_exp=None)

    # plot 2: Line plot of Number of deaths versus days since first death
    plot_params_2 = {'x_lim':[0,45],
                   'y_lim':[1,30000],
                   'x_ticks':[0,15,30,45],
                   'y_ticks':[1,10,100, 1000, 10000],
                   'title':'Number of Deaths, versus days since first death',
                   'save_name': 'Days_since_first'}

    best_fit_poly_3 = {'Korea, South':10,
                       'Italy':19,
                       'Switzerland':10,
                       'Germany':15,
                       'Denmark':7}

    best_fit_exp_3 = {'Korea, South': 'ALL',
                      'Norway': 'ALL',
                      'Japan': 'ALL',
                      'Italy': 17,
                      'Spain': 20,
                      'U.K.':20,
                      'USA':20,
                      'Switzerland':10,
                      'Denmark': 'ALL',
                      'Greece': 'ALL',
                      'Germany':15,
                      'Netherlands':15}

    ax = cpp.plot_func(df_countries, countries, plot_params_2, line_style=False, time_abs=False, d_01_type=False, pop_type=False,
              best_fit_poly=best_fit_poly_3, best_fit_exp=best_fit_exp_3, labels=False, ax=None)

    ax = cpp.plot_func(df_states, states, plot_params_2, line_style=True, time_abs=False, d_01_type=False, pop_type=False,
              best_fit_poly=None, best_fit_exp=None, labels=True, ax=ax)

    cpp.render_save_figure(plot_params_2, auto_close=False)

    ax = cpp.plot_func(df_states, states, plot_params_2, line_style=False, time_abs=False, d_01_type=False, pop_type=False,
              best_fit_poly=None, best_fit_exp=None, labels=True, ax=None)

    cpp.render_save_figure(plot_params_2, auto_close=False)

if __name__ == "__main__":
    main()
